# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install-dependencies:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Persist the workspace to be used by the next job
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-and-deploy-to-staging:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.0

    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Nuxt App
          command: yarn run build
      - run:
          name: Firebase Deploy to Staging
          command: ./node_modules/.bin/firebase deploy -P staging --token "$FIREBASE_TOKEN"

  build-and-deploy-to-production:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Nuxt App
          command: yarn run build
      - run:
          name: Firebase Deploy to Production
          command: ./node_modules/.bin/firebase deploy -P default --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install-dependencies:
          filters:
            tags:
              only: /.*/
      - build-and-deploy-to-staging:
          context: minha-cc-staging
          requires:
            - install-dependencies
          filters:
            branches:
              only: develop
      - build-and-deploy-to-production:
          context: minha-cc-production
          requires:
            - install-dependencies
          filters:
            branches:
              only: master
